export { ReactComponent as HomeIcon } from './icon-home.svg'
export { ReactComponent as PencilIcon } from './icon-pencil.svg'
export { ReactComponent as PersonIcon } from './icon-person.svg'
export { ReactComponent as ArrowLeftIcon } from './arrow-left.svg'
export { ReactComponent as MeerkatIcon } from './logo-lazysky.svg'
export { ReactComponent as GithubIcon } from './logo-github.svg'
export { ReactComponent as KakaoIcon } from './logo-kakaotalk.svg'
